package edu.wmich.lab3lperez9518;
/*
*************************************
* Programmer: Luis Perez
* Class ID: lperez9518
* Lab 3 - Paw Angel
* CIS 2610: Business Mobile Programming
* Spring 2017
* Due date: 03/23/17
* Date completed: 03/26/17
*************************************
* Program Explanation
* In this activity it will show six images in the top of the layout. Once, user clicks on an image
* the image will display in different size in the lower part of the layout.
*************************************
*/

//imports provide resource to the codes
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.Toast;
import android.content.Context;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.BaseAdapter;
import android.widget.Button;


public class GridViewActivity extends Activity {
    //Integer can hold many variables that is why we used because we are using six images
    Integer[] Dogs = {R.drawable.bu_rescued, R.drawable.bu_max, R.drawable.kiddos,
            R.drawable.bu_pajamas, R.drawable.max_christmas,R.drawable.bu_luis};
    ImageView ImageViewDogs;

    final String strRescued = "Photo of my dogs";//every click on image will show this message

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_grid_view);
        //Connecting button on xml to java. This button is to return to MainActivity
        Button btnBackGridViewActivity = (Button) findViewById(R.id.buttonBackGridViewActivity);
        btnBackGridViewActivity.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View V){
                startActivity(new Intent(GridViewActivity.this, MainActivity.class));
            }
        });
        //Connecting GridView from xml to java. Six images will be show here
        GridView gridViewDogs = (GridView) findViewById(R.id.gridViewDogs);
        //ImageView of xml to java. This is where images will be displayed when selected
        final ImageView ImageViewDogs = (ImageView) findViewById(R.id.imgDogs);
        //SetAdapter to provide data from the GridView layout
        gridViewDogs.setAdapter(new ImageAdapter(this));
        //When When user clicks on an images
        gridViewDogs.setOnItemClickListener(new OnItemClickListener() {//provides arguments
            @Override
            /*  AdapterView<?> parent: Identifies where the user clicks either inside GridView or not
                View view: which image is clicked in the GridView
                int position: remembers which item was selected
                 Long id: identifies which role is being click
             */
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // TODO Auto-generated method stub
                //Toast message once image clicked
                Toast.makeText(getBaseContext(), strRescued + (position + 1),Toast.LENGTH_SHORT).show();
                ImageViewDogs.setImageResource(Dogs[position]);//Display selected image
            }
        });
    }
    //Methods because they are performing repeated task
    public class ImageAdapter extends BaseAdapter{
        private Context context;
        //Information was autogenerated
        public ImageAdapter (Context imageConstructor){
            // TODO Auto-generated constructor stub
            context=imageConstructor;//start the progress of the image
        }
        @Override
        public int getCount(){//
            // TODO Auto-generated constructor stub
            return Dogs.length;//how many objects to show in the grid
        }
        @Override
        public Object getItem(int position) {//the click of the image selected
            // TODO Auto-generated constructor stub
            return null;
        }
        @Override
        public long getItemId(int position){
            // TODO Auto-generated constructed stub
            return 0;
        }
        @Override
        public View getView(int position, View view, ViewGroup parent){
            // TODO Auto-generated constructed stub
            ImageViewDogs = new ImageView(context);//self build GridView
            ImageViewDogs.setImageResource(Dogs[position]);//user selected
            ImageViewDogs.setScaleType(ImageView.ScaleType.FIT_XY);//scaling matching the fit
            ImageViewDogs.setLayoutParams(new GridView.LayoutParams(330,300));//height and width
            return ImageViewDogs;
        }
    }
}
